- Met the acceptance criteria
- Peer Reviewed
- All scripts merged into the shared repository
- All required documentation completed and merged into the shared repository
- Issue closed with a tag to the Pull Request associated with it
